language: bash
before_install:
  - curl -OL http://raw.github.com/xnlogic/xn-travis/master/travis-common.sh
  - chmod 755 ./travis-common.sh
  - ./travis-common.sh bootstrap
install:
  - ./travis-common.sh install_deps
script: 
  - ./travis-common.sh run_tests

after_failure:
  - ./travis-common.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
